apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metrics-collector-role
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: metrics-collector-binding
subjects:
- kind: ServiceAccount
  name: metrics-collector-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: metrics-collector-role
  apiGroup: rbac.authorization.k8s.io